#!/usr/bin/env node
/**
 * Fetches the icons from a running server and checks what actually comes back.
 *
 * scripts/check-icon-routes.mjs inspects the build output, which proves files
 * were emitted. This proves they are served, and -- more importantly -- that
 * the HTML tells the browser about them.
 *
 * That last point is the whole game. A favicon appears because the document
 * carries <link rel="icon">. Nothing in this repo writes that tag; Next
 * injects it after noticing src/app/icon.svg. If that inference ever breaks,
 * every build stays green and every page quietly loses its icon. This is the
 * only check here that would catch it.
 *
 * The apple-icon assertion is doing separate work: it is generated by Satori
 * at request time, so a build that compiles tells you nothing about whether
 * rendering throws. Checking for the PNG magic bytes is the difference
 * between "the module compiled" and "a PNG came back".
 *
 * Usage: BASE_URL=http://localhost:3000 node scripts/smoke-icons.mjs
 */

const BASE = process.env.BASE_URL ?? "http://localhost:3000";

let failures = 0;

function fail(label, detail) {
  console.error(`FAIL  ${label}\n      ${detail}`);
  failures += 1;
}

function pass(label, detail) {
  console.log(`ok    ${label}${detail ? ` -- ${detail}` : ""}`);
}

async function get(path) {
  const res = await fetch(`${BASE}${path}`, { redirect: "follow" });
  return res;
}

/* 1. The document must reference both icons. This is what a browser acts on. */
try {
  const res = await get("/");
  if (!res.ok) {
    fail("GET /", `status ${res.status}`);
  } else {
    const html = await res.text();

    /* Next may emit rel="icon", and orders attributes as it likes, so match
     * the rel value rather than a whole tag. */
    if (/rel="[^"]*\bicon\b[^"]*"/.test(html)) {
      const m = html.match(/<link[^>]*rel="[^"]*\bicon\b[^"]*"[^>]*>/);
      pass("HTML references a favicon", m ? m[0].slice(0, 120) : "");
    } else {
      fail(
        "HTML references a favicon",
        'no <link rel="icon"> in the document -- Next did not pick up ' +
          "src/app/icon.svg, so no browser will show it",
      );
    }

    if (/rel="apple-touch-icon"/.test(html)) {
      pass("HTML references the touch icon");
    } else {
      fail(
        "HTML references the touch icon",
        'no <link rel="apple-touch-icon"> -- src/app/apple-icon.tsx was not ' +
          "picked up",
      );
    }
  }
} catch (err) {
  fail("GET /", err.message);
}

/* 2. The favicon itself. */
try {
  const res = await get("/icon.svg");
  const type = res.headers.get("content-type") ?? "";
  if (!res.ok) {
    fail("GET /icon.svg", `status ${res.status}`);
  } else if (!type.includes("svg")) {
    fail("GET /icon.svg", `content-type was ${type}`);
  } else {
    const body = await res.text();
    if (!body.includes("<path")) {
      fail("GET /icon.svg", "response contains no path data");
    } else {
      pass("GET /icon.svg", `${type}, ${body.length} bytes`);
    }
  }
} catch (err) {
  fail("GET /icon.svg", err.message);
}

/* 3. The touch icon must be a real PNG, not a Satori stack trace. */
try {
  const res = await get("/apple-icon");
  const type = res.headers.get("content-type") ?? "";
  if (!res.ok) {
    fail("GET /apple-icon", `status ${res.status}`);
  } else {
    const buf = new Uint8Array(await res.arrayBuffer());
    const PNG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
    const isPng =
      buf.length > 8 && PNG.every((b, i) => buf[i] === b);
    if (!isPng) {
      fail(
        "GET /apple-icon",
        `not a PNG (content-type ${type}, ${buf.length} bytes). Satori ` +
          "probably threw while rendering.",
      );
    } else {
      pass("GET /apple-icon", `PNG, ${buf.length} bytes`);
    }
  }
} catch (err) {
  fail("GET /apple-icon", err.message);
}

/* 4. The downloadable brand assets under public/. */
try {
  const res = await get("/brand/focii-icon.svg");
  if (!res.ok) {
    fail("GET /brand/focii-icon.svg", `status ${res.status}`);
  } else {
    const body = await res.text();
    if (!body.includes("<path")) {
      fail("GET /brand/focii-icon.svg", "no path data in response");
    } else {
      pass("GET /brand/focii-icon.svg", `${body.length} bytes`);
    }
  }
} catch (err) {
  fail("GET /brand/focii-icon.svg", err.message);
}

if (failures > 0) {
  console.error(`\n${failures} icon check(s) failed against ${BASE}`);
  process.exit(1);
}

console.log(`\nall icon checks passed against ${BASE}`);
